version: "3.9"

services:
  fsb:
    image: ghcr.io/everythingsuckz/fsb
    container_name: fsb
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./fsb.env:/app/fsb.env
    ports:
      - "${PORT:-8038}:${PORT:-8038}"